# -*- coding: utf-8 -*- 

'''<html>
<body>
<p>
'''

# unicode string, with unicode characters in utf-8 encoding
u"Μπορώ να φάω σπασμένα γυαλιά χωρίς να πάθω τίποτα."

'<p>'

# plain 8-bit string in utf-8
# this will display properly only if outputEncoding is utf-8
"Aš galiu valgyti stiklą ir jis manęs nežeidžia"

'<p>'

# unicode string with unicode escape sequences
u"Cette phrase contient le caract\u00e8re <b>\u00e8</b>"

'''</body>
</html>
'''
